(function(e,f){var d={tolerance:2,delay:100,glyphs:"",success:function(){},error:function(){},timeout:5E3,weight:"400",style:"normal"},h="display:block position:absolute top:-999px left:-999px font-size:48px width:auto height:auto line-height:normal margin:0 padding:0 font-variant:normal white-space:nowrap".split(" "),a=function(){this.fontFamily="";this.appended=!1;this.parent=this.sansSerif=this.serif=void 0;this.options={}};a.prototype.getMeasurements=function(){return{sansSerif:{width:this.sansSerif.offsetWidth,
height:this.sansSerif.offsetHeight},serif:{width:this.serif.offsetWidth,height:this.serif.offsetHeight}}};a.prototype.load=function(){function l(c){return h.concat(["font-weight:"+k.weight,"font-style:"+k.style]).concat("font-family:"+c).join(";")}function c(c,a,b){return Math.abs(c.width-a.offsetWidth)>b||Math.abs(c.height-a.offsetHeight)>b}var b=new Date,a=this,g=a.serif,d=a.sansSerif,m=a.parent,n=a.appended,p,k=a.options,q=k.reference,t='<div style="%s">AxmTYklsjo190QW</div>'.replace(/\%s/,l("sans-serif")),
u='<div style="%s">AxmTYklsjo190QW</div>'.replace(/\%s/,l("serif"));m||(m=a.parent=f.createElement("div"));m.innerHTML=t+u;d=a.sansSerif=m.firstChild;g=a.serif=d.nextSibling;k.glyphs&&(d.innerHTML+=k.glyphs,g.innerHTML+=k.glyphs);(function r(){q||(q=f.body);!n&&q&&(q.appendChild(m),n=a.appended=!0,p=a.getMeasurements(),d.style.fontFamily=a.fontFamily+", sans-serif",g.style.fontFamily=a.fontFamily+", serif");n&&p&&(c(p.sansSerif,d,k.tolerance)||c(p.serif,g,k.tolerance))?k.success():(new Date).getTime()-
b.getTime()>k.timeout?k.error():!n&&"requestAnimationFrame"in window?e.requestAnimationFrame(r):e.setTimeout(r,k.delay)})()};a.prototype.cleanFamilyName=function(a){return a.replace(/[\'\"]/g,"").toLowerCase()};a.prototype.cleanWeight=function(a){return""+({normal:"400",bold:"700"}[a]||a)};a.prototype.checkFontFaces=function(a){var c=this;f.fonts.forEach(function(b){c.cleanFamilyName(b.family)===c.cleanFamilyName(c.fontFamily)&&c.cleanWeight(b.weight)===c.cleanWeight(c.options.weight)&&b.style===
c.options.style&&b.load().then(function(){c.options.success();e.clearTimeout(a)})})};a.prototype.init=function(a,c){var b,h;for(h in d)c.hasOwnProperty(h)||(c[h]=d[h]);this.options=c;this.fontFamily=a;!c.glyphs&&"fonts"in f?(c.timeout&&(b=e.setTimeout(function(){c.error()},c.timeout)),this.checkFontFaces(b)):this.load()};e.FontFaceOnload=function(l,c){var b=new a;b.init(l,c);return b}})(this,this.document);
(function(e){function f(c,b){(d(c,b)?a:h)(c,b)}var d,h,a;"classList"in document.documentElement?(d=function(a,b){return a.classList.contains(b)},h=function(a,b){a.classList.add(b)},a=function(a,b){a.classList.remove(b)}):(d=function(a,b){return(new RegExp("(^|\\s+)"+b+"(\\s+|$)")).test(a.className)},h=function(a,b){d(a,b)||(a.className=a.className+" "+b)},a=function(a,b){a.className=a.className.replace(new RegExp("(^|\\s+)"+b+"(\\s+|$)")," ")});var l={hasClass:d,addClass:h,removeClass:a,toggleClass:f,
has:d,add:h,remove:a,toggle:f};"function"===typeof define&&define.amd?define(l):e.classie=l})(window);
(function(e){function f(a,l){var c=a.offsetHeight,b=e.pageYOffset||h.scrollTop;var d=h.clientHeight,g=e.innerHeight;var d=b+(d<g?g:d),g=a,f=0;do isNaN(g.offsetTop)||(f+=g.offsetTop),isNaN(g.offsetLeft);while(g=g.offsetParent);g=f;return g+c*(l||0)<=d&&g+c>=b}function d(a,d){this.el=a;var c=this.defaults,b;for(b in d)d.hasOwnProperty(b)&&(c[b]=d[b]);this.options=c;this._init()}var h=e.document.documentElement;d.prototype={defaults:{viewportFactor:.4},_init:function(){this.sections=Array.prototype.slice.call(this.el.querySelectorAll(".slide"));
this.didScroll=!1;var a=this;this.sections.forEach(function(a,c){f(a)||classie.add(a,"inert")});e.addEventListener("scroll",function(){a.didScroll||(a.didScroll=!0,setTimeout(function(){a._scrollPage()},60))},!1);e.addEventListener("resize",function(){a.resizeTimeout&&clearTimeout(a.resizeTimeout);a.resizeTimeout=setTimeout(function(){a._scrollPage();a.resizeTimeout=null},200)},!1)},_scrollPage:function(){var a=this;this.sections.forEach(function(d,c){f(d,a.options.viewportFactor)?classie.add(d,"active"):
(classie.add(d,"inert"),classie.remove(d,"active"))});this.didScroll=!1}};e.cbpScroller=d})(window);var docElem=window.document.documentElement;function getViewportH(){var e=docElem.clientHeight,f=window.innerHeight;return e<f?f:e}function getViewportW(){var e=docElem.clientWidth,f=window.innerWidth;return e<f?f:e}var screenWidth=getViewportW(),root=document.getElementsByTagName("html")[0];
if(768<screenWidth&&!classie.has(root,"oldie")){root.className+=" js";var screenHeight=getViewportH();document.getElementsByClassName("slides")[0].style.height=screenHeight+"px";new cbpScroller(document.getElementsByClassName("home")[0])}FontFaceOnload("montserratregular",{success:function(){document.documentElement.className+=" font-loaded"}});
